(() => {
  // <stdin>
  (function() {
    const bar = document.querySelector(".filter-bar");
    if (!bar) return;
    const buttons = Array.from(bar.querySelectorAll(".filter-button"));
    const cards = Array.from(document.querySelectorAll(".card"));
    function setActive(btn) {
      buttons.forEach((b) => b.classList.toggle("active", b === btn));
    }
    function applyFilter(tag) {
      const all = tag === "\u5168\u90E8";
      cards.forEach((card) => {
        const tags = (card.getAttribute("data-tags") || "").split(",").filter(Boolean);
        const show = all || tags.includes(tag);
        card.style.display = show ? "block" : "none";
      });
    }
    bar.addEventListener("click", (e) => {
      const btn = e.target.closest(".filter-button");
      if (!btn) return;
      setActive(btn);
      applyFilter(btn.dataset.tag);
    });
  })();
  console.log("This site was generated by Hugo.");
})();
